// Autogenerated from Pigeon (v3.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name
// @dart = 2.12
import 'dart:async';
import 'dart:typed_data' show Uint8List, Int32List, Int64List, Float64List;

import 'package:flutter/foundation.dart' show WriteBuffer, ReadBuffer;
import 'package:flutter/services.dart';

class NfcResult {
  NfcResult({
    this.cardNumber,
    this.expiryDate,
    this.aid,
    this.cardType,
  });

  String? cardNumber;
  Date? expiryDate;
  String? aid;
  String? cardType;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['cardNumber'] = cardNumber;
    pigeonMap['expiryDate'] = expiryDate?.encode();
    pigeonMap['aid'] = aid;
    pigeonMap['cardType'] = cardType;
    return pigeonMap;
  }

  static NfcResult decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return NfcResult(
      cardNumber: pigeonMap['cardNumber'] as String?,
      expiryDate: pigeonMap['expiryDate'] != null
          ? Date.decode(pigeonMap['expiryDate']!)
          : null,
      aid: pigeonMap['aid'] as String?,
      cardType: pigeonMap['cardType'] as String?,
    );
  }
}

class Date {
  Date({
    this.month,
    this.year,
  });

  String? month;
  String? year;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['month'] = month;
    pigeonMap['year'] = year;
    return pigeonMap;
  }

  static Date decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return Date(
      month: pigeonMap['month'] as String?,
      year: pigeonMap['year'] as String?,
    );
  }
}

class _NfcApiCodec extends StandardMessageCodec {
  const _NfcApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is Date) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else 
    if (value is NfcResult) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else 
{
      super.writeValue(buffer, value);
    }
  }
  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:       
        return Date.decode(readValue(buffer)!);
      
      case 129:       
        return NfcResult.decode(readValue(buffer)!);
      
      default:      
        return super.readValueOfType(type, buffer);
      
    }
  }
}

class NfcApi {
  /// Constructor for [NfcApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NfcApi({BinaryMessenger? binaryMessenger}) : _binaryMessenger = binaryMessenger;

  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _NfcApiCodec();

  Future<NfcResult> scanNfcTag() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.NfcApi.scanNfcTag', codec, binaryMessenger: _binaryMessenger);
    final Map<Object?, Object?>? replyMap =
        await channel.send(null) as Map<Object?, Object?>?;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyMap['error'] != null) {
      final Map<Object?, Object?> error = (replyMap['error'] as Map<Object?, Object?>?)!;
      throw PlatformException(
        code: (error['code'] as String?)!,
        message: error['message'] as String?,
        details: error['details'],
      );
    } else if (replyMap['result'] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyMap['result'] as NfcResult?)!;
    }
  }

  Future<void> stopScan() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.NfcApi.stopScan', codec, binaryMessenger: _binaryMessenger);
    final Map<Object?, Object?>? replyMap =
        await channel.send(null) as Map<Object?, Object?>?;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyMap['error'] != null) {
      final Map<Object?, Object?> error = (replyMap['error'] as Map<Object?, Object?>?)!;
      throw PlatformException(
        code: (error['code'] as String?)!,
        message: error['message'] as String?,
        details: error['details'],
      );
    } else {
      return;
    }
  }
}
